---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: cncjs
  name: cncjs-cert
spec:
  secretName: cncjs-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - 'cnc.high.am'
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      - 'cnc.high.am'
    
